export default allCategories = [
    { id: 0, category: 'technology' },
    { id: 1, category: 'food' },
    { id: 2, category: 'travel' },
    { id: 3, category: 'music' },
    { id: 4, category: 'sport' },
    { id: 5, category: 'fashion' },
    { id: 6, category: 'health' },
    { id: 7, category: 'business' },
    { id: 8, category: 'science' },
    { id: 9, category: 'education' },
    { id: 10, category: 'art' },
    { id: 11, category: 'superheroes' },
    { id: 12, category: 'books' },
    { id: 13, category: 'fitness' },
    { id: 14, category: 'home' },
    { id: 15, category: 'gardening' },
    { id: 16, category: 'cars' },
    { id: 17, category: 'pets' },
    { id: 18, category: 'movies' },
    { id: 19, category: 'science-fiction' },
    { id: 20, category: 'explore' },
    { id: 21, category: 'countries' },
    { id: 22, category: 'series' },
    { id: 23, category: 'celebrities' },
];

export const iconMap = {
    //Icons
    technology: require("../assets/icons/technology.png"),
    sport: require("../assets/icons/sport.png"),
    movies: require("../assets/icons/movies.png"),
    series: require("../assets/icons/series.png"),
    explore: require("../assets/icons/explore.png"),
    travel: require("../assets/icons/travel.png"),
    music: require("../assets/icons/music.png"),
    science: require("../assets/icons/science.png"),
    celebrities: require("../assets/icons/celebrities.png"),
    food: require("../assets/icons/food.png"),
    fashion: require("../assets/icons/fashion.png"),
    health: require("../assets/icons/health.png"),
    superheroes: require("../assets/icons/superheros.png"),
    business: require("../assets/icons/business.png"),
    education: require("../assets/icons/education.png"),
    art: require("../assets/icons/art.png"),
    books: require("../assets/icons/books.png"),
    fitness: require("../assets/icons/fitness.png"),
    home: require("../assets/icons/home.png"),
    gardening: require("../assets/icons/gardening.png"),
    cars: require("../assets/icons/cars.png"),
    pets: require("../assets/icons/pets.png"),
    scifi: require("../assets/icons/scifi.png"),
    countries: require("../assets/icons/countries.png"),
  
    level: require("../assets/icons/level.jpg"),
  };

export const avatarMap = {
    //Icons
    technology: require("../assets/avatars/technology.jpg"),
    sport: require("../assets/avatars/sport.jpg"),
    movies: require("../assets/avatars/movies.jpg"),
    series: require("../assets/avatars/series.jpg"),
    explore: require("../assets/avatars/explore.jpg"),
    travel: require("../assets/avatars/travel.jpg"),
    music: require("../assets/avatars/music.jpg"),
    science: require("../assets/avatars/science.jpg"),
    celebrities: require("../assets/avatars/celebrities.jpg"),
    food: require("../assets/avatars/food.jpg"),
    fashion: require("../assets/avatars/fashion.jpg"),
    health: require("../assets/avatars/health.jpg"),
    superheroes: require("../assets/avatars/superheroes.jpg"),
    business: require("../assets/avatars/business.jpg"),
    education: require("../assets/avatars/education.jpg"),
    art: require("../assets/avatars/art.jpg"),
    books: require("../assets/avatars/books.jpg"),
    fitness: require("../assets/avatars/fitness.jpg"),
    home: require("../assets/avatars/home.jpg"),
    gardening: require("../assets/avatars/gardening.jpg"),
    cars: require("../assets/avatars/cars.jpg"),
    pets: require("../assets/avatars/pets.jpg"),
    scifi: require("../assets/avatars/scifi.jpg"),
    countries: require("../assets/avatars/countries.jpg"),

    default: require("../assets/avatars/default.jpg"),
  };